### PR TITLE
Feature/include merged refs

### PR DESCRIPTION
**Pull request by Averus-a**
Contains added features:
1. Hardcoded x:Type/x:Static checks replaced with actual namespace (Now looks for `http://schemas.microsoft.com/winfx/2006/xaml` namespace in root's attributes)
2. Adds an optional parameter to include merged ResourceDictionary links from resources (otherwise we can't preserve loading order without doing additional changes in some cases)
3. Seeks for Markdown syntax in attribute values when namespace should be renamed to fix them.

### CODE REVIEW

**Comment by batzen** [comment]
1. Nice catch. Totally forgot about that.

2. I don't think it's necessary to add the ability to include merged dictionaries.
Fluent.Ribbon solves this by not generating a Generic.xaml, but a Styles.xaml and have the required order of merged dictionaries in a hand crafted Generic.xaml. 
That guarantees the correct order and does not require special logic in the generator.
So to be clear: I don't think this part should be merged.

3. Also totally missed that during testing. I am not sure if the current namespace renaming should stay in place or if the tool should simply fail if different prefixes are found for the same namespace, but that's for the future.

**Comment by Averus-a** [comment]
Hello, thanks for having a time for looking into it.

About 2 (including merged references) feature:

I am tried to solve an issue with missing resources in case like this:
image
After merging xamls in both Assembly1/Assembly2 the resources from Assembly1 are missing from a scope of Assembly2 generated file if they are not included as merged dictionary on current level (inside generated file) or place resource with this key directly in App.xaml. Including generic.xaml reference from Assembly1 in App.xaml in merged dictionaries doesn't help 😔

I suspect it creates a duplicate copy of dictionary in this way, so i've added this option as optional parameter (false by default) as it's specific case. Without it we'll forced to manual edit generated file.

Also, to be clear: this option only keeps references on ResourceDictionaries which aren't processed by XamlCombine 

About 3
Personally, i like your idea of renaming namespaces in automatic way (works smooth for our projects). Would be nice to keep it as optional flag if you decide to change logic in the future 😀

**Comment by batzen** [comment]
I will merge your changes, but refactor it slightly afterwards.

Could you provide a sample project that showcases why we need the merged dictionary option?
I still don't like that being added as it's quite dangerous and should be solved the way Fluent.Ribbon handles it.
Maybe i can show that on your provided sample. ;-)

**Comment by Averus-a** [comment]
Thanks. I'll try to provide sample solution on this week.

**Comment by GeertvanHorrik** [comment]
Thank you for merging. Will this version be available as prerelease on NuGet?

**Comment by batzen** [comment]
Will put it on nuget tomorrow.

**Comment by batzen** [comment]
@GeertvanHorrik just pushed to NuGet. Should be available soon.

**Pull request merged**
